///////////////////////////////////////////////////////////
//  ISelectable.cs
//  Implementation of the Interface ISelectable
//  Generated by Enterprise Architect
//  Created on:      09-Okt-2024 08:12:40
//  Original author: vistmm
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface ISelectable  {

}//end ISelectable