///////////////////////////////////////////////////////////
//  ITarget.cs
//  Implementation of the Interface ITarget
//  Generated by Enterprise Architect
//  Created on:      09-Okt-2024 08:12:41
//  Original author: vistmm
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface ITarget  {

}//end ITarget